const translations={navAbout:'关于',navPapers:'论文',navEducation:'教育',navHonors:'荣誉',navService:'服务',profileLabel:'个人学术主页',position:'博士研究生',affiliation:'中国科学院信息工程研究所<br>中国科学院大学',location:'中国 · 北京',interestsHeading:'研究方向',interest1:'加密流量分析',interest2:'网站指纹识别',interest3:'网络协议安全',interest4:'大模型与智能体安全',graduation:'预计毕业时间<br><strong>2027 年 1 月</strong>',aboutTitle:'个人简介',bio:'我是<strong>中国科学院信息工程研究所、中国科学院大学</strong>的博士研究生，导师为<strong><a class="person-link" href="https://people.ucas.ac.cn/~liuqingyun" target="_blank" rel="noopener noreferrer">刘庆云</a>正高级工程师</strong>。我于 2021 年硕士入学，2023 年进入硕博连读阶段，预计于 <strong>2027 年 1 月毕业</strong>。',researchBio:'我的研究聚焦<strong>加密流量分析、网站指纹识别与网络协议安全</strong>，近期也关注大模型智能体的通信安全。我结合协议分析、真实世界测量与机器学习，研究网络系统中的信息泄露与安全风险。第一作者代表作包括 <strong>NDSS 2027</strong>（已录用）、<strong>INFOCOM 2026</strong> 和 <strong>WWW 2025</strong>（Oral）。',incoming:'<strong>未来去向：</strong>即将加入<strong>中关村国家实验室，<a class="person-link" href="https://baike.baidu.com/en/item/Yun%20Xiaochun/652366" target="_blank" rel="noopener noreferrer">云晓春院士</a>团队</strong>。',newsTitle:'近期动态',news1:'论文 <strong>Silent Surrender</strong> 被 <strong>NDSS 2027</strong> 录用。',news2:'获得<strong>博士研究生国家奖学金</strong>。',news3:'两篇关于加密流量可观察性与缓存感知网站指纹识别的第一作者论文被 <strong>WISE 2026</strong> 录用。',papersTitle:'精选论文',paperContact:'欢迎联系交流论文与研究 ↗',paperNote:'优先展示代表性成果，作者列表中突出标注本人姓名。',otherTitle:'其他精选论文',educationTitle:'教育经历',expected:'（预计）',degree1:'博士研究生阶段',educationOrg:'中国科学院信息工程研究所 / 中国科学院大学',advisor:'导师：<a class="person-link" href="https://people.ucas.ac.cn/~liuqingyun" target="_blank" rel="noopener noreferrer">刘庆云</a>正高级工程师',track:'2023 年进入硕博连读阶段，预计 2027 年 1 月毕业。',degree2:'硕士研究生阶段',transfer:'2023 年转入硕博连读。',honorsTitle:'重要荣誉与奖励',award1:'<strong>博士研究生国家奖学金</strong>',award2:'中国科学院大学<strong>三好学生标兵</strong>',award3:'DataCon 大数据安全分析竞赛 · 互联网威胁分析赛道<strong>第六名 / 二等奖</strong>',award4:'DataCon 大数据安全分析竞赛 · 网络基础设施安全赛道<strong>第一名 / 一等奖</strong>',award5:'中国科学院大学三好学生（连续三年）',serviceTitle:'学术服务',reviewer:'会议审稿人',teaching:'课程助教',course:'中国科学院大学《网络信息内容安全》<br><span class="muted">2023–2024、2024–2025 学年春季学期 · 授课教师：<a class="person-link" href="https://people.ucas.ac.cn/~zhuyujia" target="_blank" rel="noopener noreferrer">朱宇佳</a></span>',footer:'© 2026 程逸飞 · 更新于 2026 年 10 月',backTop:'返回顶部 ↑'};
Object.assign(translations, {"bio":"我是<strong>中国科学院信息工程研究所、中国科学院大学网络空间安全专业</strong>博士研究生，导师为<strong><a class=\"person-link\" href=\"https://people.ucas.ac.cn/~liuqingyun\" target=\"_blank\" rel=\"noopener noreferrer\">刘庆云</a>正高级工程师</strong>，并由<strong><a class=\"person-link\" href=\"https://people.ucas.ac.cn/~zhuyujia\" target=\"_blank\" rel=\"noopener noreferrer\">朱宇佳</a>副研究员</strong>给予直接科研指导。我于 2021 年毕业于<strong>南京邮电大学信息安全专业</strong>，同年保研至信工所，2023 年进入硕博连读阶段，预计于 <strong>2027 年 1 月毕业</strong>。","degree1":"博士研究生 · 网络空间安全","degree2":"硕士研究生 · 网络空间安全","advisor":"导师：<a class=\"person-link\" href=\"https://people.ucas.ac.cn/~liuqingyun\" target=\"_blank\" rel=\"noopener noreferrer\">刘庆云</a>正高级工程师 · 科研指导：<a class=\"person-link\" href=\"https://people.ucas.ac.cn/~zhuyujia\" target=\"_blank\" rel=\"noopener noreferrer\">朱宇佳</a>副研究员","transfer":"2021 年保研入学，2023 年转入硕博连读。","navNews":"动态","degree3":"本科 · 信息安全","undergradOrg":"南京邮电大学 · 计算机学院、软件学院、网络空间安全学院","undergradNote":"2017–2021 年就读，毕业后保研至中国科学院信息工程研究所。","award6":"全国大学生数学建模竞赛 · <strong>国家一等奖</strong>","award7":"国际机器人奥林匹克竞赛（IROC）国际赛 · 机器人 DV 项目<strong>最佳设计奖</strong>"});
for (const key of Object.keys(translations)) {
  translations[key] = translations[key].replaceAll('中国科学院大学', '<a href="https://www.ucas.ac.cn/" target="_blank" rel="noopener noreferrer">中国科学院大学</a>');
}
const conferences={silent:'Network and Distributed System Security Symposium (NDSS), 2027',star:'IEEE International Conference on Computer Communications (INFOCOM), 2026',holmes:'The ACM Web Conference (WWW), 2025'};
let language='en';try{language=localStorage.getItem('language')==='zh'?'zh':'en'}catch{}
const originalText=new Map();document.querySelectorAll('[data-i18n]').forEach(el=>originalText.set(el,el.innerHTML));
function render(){const zh=language==='zh',idx=zh?1:0;document.documentElement.lang=zh?'zh-CN':'en';document.title=zh?'程逸飞 | 个人学术主页':'Yifei Cheng (程逸飞) | Academic Homepage';originalText.forEach((value,el)=>el.innerHTML=zh?(translations[el.dataset.i18n]||value):value);const toggle=document.getElementById('language');toggle.textContent=zh?'EN':'中文';toggle.setAttribute('aria-label',zh?'Switch to English':'切换为中文');document.querySelector('nav').setAttribute('aria-label',zh?'主导航':'Main navigation');document.querySelector('.skip').textContent=zh?'跳至正文':'Skip to content';document.getElementById('close-citation').setAttribute('aria-label',zh?'关闭引用':'Close citation');document.getElementById('copy-citation').textContent=zh?'复制引用':'Copy citation';
document.getElementById('featured-papers').innerHTML=papers.map((p,i)=>`<article class="paper" id="paper-${p.id}">${p.image?`<img class="paper-image" src="${p.image}" alt="${p.name} overview" loading="lazy">`:''}<div class="paper-top"><span class="venue">${p.venue}</span><span class="paper-rank">CCF-A · ${zh?'第一作者':'First author'}</span>${p.status?`<span class="status">${p.status[idx]}</span>`:''}</div><h3>${p.links.length?`<a href="${p.links[0][2]}" target="_blank" rel="noopener noreferrer">${p.name}: ${p.subtitle}</a>`:`${p.name}: ${p.subtitle}`}</h3><p class="authors">${p.authors}</p><p class="paper-conference">${conferences[p.id]}</p><div class="paper-links">${p.links.map(l=>`<a href="${l[2]}" target="_blank" rel="noopener noreferrer">${l[idx]}</a>`).join('')}${p.bib?`<button data-cite="${i}" aria-haspopup="dialog">BibTeX</button>`:`<span class="availability">${zh?'已录用，待出版':'Accepted, to appear'}</span>`}</div></article>`).join('');
document.getElementById('additional-papers').innerHTML=additional.map(p=>`<article class="compact-paper"><span class="compact-venue">${p[2]}</span><div><h4>${p[1]}</h4><p>${zh?`第${['','一','二','三','四'][p[3]]}作者`:`${{1:'First',2:'Second',4:'Fourth'}[p[3]]} author`}${p[4]?(zh?' · 已录用':' · Accepted'):''}</p></div></article>`).join('');document.querySelectorAll('[data-cite]').forEach(btn=>btn.addEventListener('click',()=>{document.getElementById('citation-text').textContent=papers[Number(btn.dataset.cite)].bib;document.getElementById('copy-status').textContent='';document.getElementById('citation-dialog').showModal()}));}
document.getElementById('language').addEventListener('click',()=>{language=language==='en'?'zh':'en';try{localStorage.setItem('language',language)}catch{}render()});
document.getElementById('close-citation').addEventListener('click',()=>document.getElementById('citation-dialog').close());document.getElementById('citation-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
document.getElementById('copy-citation').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.getElementById('citation-text').textContent);document.getElementById('copy-status').textContent=language==='zh'?'已复制到剪贴板。':'Copied to clipboard.'}catch{document.getElementById('copy-status').textContent=language==='zh'?'请选中上方文本，手动复制。':'Please select and copy the citation above.'}});
render();
// Keep every section reachable below the fixed header, including near the page end.
const navLinks=[...document.querySelectorAll('.nav-links>a')];
const navSections=navLinks.map(a=>document.querySelector(a.hash));
const navTail=document.createElement('div');navTail.className='nav-tail';navTail.setAttribute('aria-hidden','true');document.body.append(navTail);
function navOffset(){return document.querySelector('.header').getBoundingClientRect().height+22}
function updateNavigation(){
 const offset=navOffset();document.documentElement.style.scrollPaddingTop=offset+'px';
 const tailHeight=navTail.getBoundingClientRect().height;
 const last=navSections.at(-1);
 const endSpace=document.documentElement.scrollHeight-tailHeight-(last.getBoundingClientRect().top+scrollY);
 navTail.style.height=Math.max(0,innerHeight-offset-endSpace+1)+'px';
 const active=navSections.filter(section=>section.getBoundingClientRect().top<=offset+3).at(-1)||navSections[0];
 navLinks.forEach(link=>{if(link.hash==='#'+active.id)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current')});
}
let navigationFrame;
function scheduleNavigation(){if(navigationFrame)return;navigationFrame=requestAnimationFrame(()=>{navigationFrame=null;updateNavigation()})}
function goToSection(hash){const section=document.querySelector(hash);if(!section)return;updateNavigation();section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});section.setAttribute('tabindex','-1');section.focus({preventScroll:true})}
navLinks.forEach(link=>link.addEventListener('click',event=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();if(location.hash!==link.hash)history.pushState(null,'',link.hash);goToSection(link.hash)}));
addEventListener('scroll',scheduleNavigation,{passive:true});addEventListener('resize',scheduleNavigation);addEventListener('hashchange',()=>{if(navLinks.some(a=>a.hash===location.hash))goToSection(location.hash)});
new ResizeObserver(scheduleNavigation).observe(document.getElementById('main'));
addEventListener('load',()=>{updateNavigation();if(navLinks.some(a=>a.hash===location.hash))goToSection(location.hash)});
document.getElementById('language').addEventListener('click',scheduleNavigation);
updateNavigation();
