const translations = {
  identitySub:'网络安全研究', navResearch:'研究', navAbout:'关于', navContact:'联系',role:'博士研究生 · 网络空间安全',hello:'你好，我是程逸飞。',headline:'理解加密之后，<br>仍然<em>可见</em>的<br>世界。',heroDescription:'我关注加密流量与网络系统安全，通过协议分析、机器学习与真实世界测量，研究加密通信中的信息泄露。',explore:'了解代表性研究',figureCaption:'内容被加密，模式仍然可见。',institute:'中国科学院信息工程研究所',university:'中国科学院大学',researchLabel:'01 / 代表性成果',researchTitle:'聚焦研究<span class="accent">。</span>',researchDescription:'探索加密通信中<br>仍然暴露的信息与安全边界。',additionalTitle:'其他精选论文',selectedNote:'部分研究成果',aboutLabel:'02 / 关于我',aboutTitle:'探究表象之下，<br>理解系统本质<span class="accent">。</span>',bio:'我是中国科学院信息工程研究所、中国科学院大学的博士研究生，导师为刘庆云正高级工程师。我的研究聚焦网站指纹识别、加密流量分析与网络协议安全。',approach:'我结合实证测量与机器学习方法，理解现代网络系统中的信息泄露，探索加密内容与可观察行为之间的边界。',topic1:'加密流量分析',topic2:'网站指纹识别',topic3:'协议安全',honors:'重要荣誉',award1:'博士研究生国家奖学金',award1org:'中华人民共和国教育部',award2:'DataCon 大数据安全分析竞赛 · 第一名',award2org:'网络基础设施安全赛道 · 一等奖',award3:'三好学生标兵',award3org:'中国科学院大学',service:'学术服务',reviewer:'审稿人',teaching:'课程助教',course:'网络信息内容安全<br>中国科学院大学 · 2023–2025',contactLabel:'03 / 学术交流',contactTitle:'让想法，<br><em>彼此连接。</em>',contactDescription:'欢迎交流研究想法、探讨学术合作，<br>或就论文与数据集联系我。',footerNote:'从一个问题出发：我们究竟能够观察到什么？',backTop:'返回顶部 ↑',education:'<strong>中国科学院信息工程研究所 / 中国科学院大学</strong>2021 年硕士入学 · 2023 年硕博连读<br>预计 2027 年 1 月博士毕业',nextStep:'即将加入中关村实验室，云晓春院士团队。'
};
const papers = [
  {id:'silent',name:'Silent Surrender',subtitle:'Measuring MitM-Induced TLS Downgrades in LLM Agents',venue:'NDSS 2027',status:['ACCEPTED','已录用'],authors:null,summary:['Examining TLS security boundaries in LLM agents through measurement of man-in-the-middle-induced downgrades.','通过测量中间人诱导的 TLS 降级行为，研究大语言模型智能体的通信安全边界。'],links:[],art:'tls'},
  {id:'star',name:'STAR',subtitle:'Semantic-Traffic Alignment and Retrieval for Zero-Shot HTTPS Website Fingerprinting',venue:'INFOCOM 2026',authors:'<strong>Yifei Cheng</strong>, Yujia Zhu, Baiyang Li, Xinhao Deng, Yitong Cai, Yaochen Ren, Qingyun Liu',summary:['Recognizing unseen websites by aligning encrypted traffic with website semantics — without collecting training traffic from the target sites.','将加密流量与网站语义对齐，在无需采集目标网站训练流量的情况下识别未见网站。'],links:[['Paper','论文','https://arxiv.org/abs/2512.17667'],['Code','代码','https://github.com/2654400439/STAR-Website-Fingerprinting'],['Dataset','数据集','https://doi.org/10.5281/zenodo.17060855']],bib:'@inproceedings{cheng2026star,\n  title={STAR: Semantic-Traffic Alignment and Retrieval for Zero-Shot HTTPS Website Fingerprinting},\n  author={Cheng, Yifei and Zhu, Yujia and Li, Baiyang and Deng, Xinhao and Cai, Yitong and Ren, Yaochen and Liu, Qingyun},\n  booktitle={IEEE INFOCOM 2026-IEEE Conference on Computer Communications},\n  pages={1--10},\n  year={2026},\n  organization={IEEE}\n}',art:'star'},
  {id:'holmes',name:'HOLMES & WATSON',subtitle:'A Robust and Lightweight HTTPS Website Fingerprinting through HTTP Version Parallelism',venue:'WWW 2025',status:['ORAL','口头报告'],authors:'<strong>Yifei Cheng</strong>, Yujia Zhu, Baiyang Li, Peishuai Sun, Yong Ding, Xinhao Deng, Qingyun Liu',summary:['Using the parallel behavior of HTTP versions to build compact, robust fingerprints of encrypted website visits.','利用 HTTP 多版本并行行为，构建轻量、鲁棒的加密网站访问指纹。'],links:[['Paper','论文','https://doi.org/10.1145/3696410.3714578'],['Code','代码','https://github.com/2654400439/H123-Website-Fingerprinting'],['Dataset','数据集','https://zenodo.org/records/14727250']],bib:'@inproceedings{cheng2025holmes,\n  title={HOLMES \\& WATSON: A Robust and Lightweight HTTPS Website Fingerprinting through HTTP Version Parallelism},\n  author={Cheng, Yifei and Zhu, Yujia and Li, Baiyang and Sun, Peishuai and Ding, Yong and Deng, Xinhao and Liu, Qingyun},\n  booktitle={Proceedings of the ACM on Web Conference 2025},\n  pages={1078--1092},\n  year={2025},\n  doi={10.1145/3696410.3714578}\n}',art:'holmes'}
];
const additional = [
  ['2026','How Web Optimization Shapes Encrypted Traffic Observability','WISE 2026',1,true],
  ['2026','Beyond the clean slate: robust website fingerprinting via cache-time trajectories','WISE 2026',1,true],
  ['2026','OPTICS: Open-set Encrypted Traffic Classification via Conditional Diffusion Models','ICNP 2026',4,true],
  ['2025','Knocking on IP: Unveiling Websites through Cache-Aware Fingerprinting','ICASSP 2025',2,false],
  ['2025','QUIC安全研究综述：协议、实现和生态','通信学报',2,false]
];
function illustration(type){
 const start='<svg viewBox="0 0 350 239" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Conceptual research illustration, not experimental data">';
 if(type==='tls')return start+'<rect width="350" height="239" fill="#e9e8e0"/><g fill="none" stroke="#cdd0c5"><circle cx="175" cy="114" r="82"/><circle cx="175" cy="114" r="61" stroke-dasharray="2 5"/><path d="M30 114H320M175 26V202"/></g><g fill="#f6f5f0" stroke="#6c8276"><rect x="35" y="89" width="67" height="49" rx="4"/><rect x="248" y="89" width="67" height="49" rx="4"/></g><path d="M102 114H146M203 114H248" stroke="#415d52" stroke-width="1.5"/><path d="M154 102V89a21 21 0 0 1 42 0" fill="none" stroke="#a44c34" stroke-width="2"/><rect x="146" y="103" width="58" height="46" rx="5" fill="#a44c34"/><circle cx="175" cy="121" r="4" fill="#f6f5f0"/><path d="M175 122v11" stroke="#f6f5f0" stroke-width="2"/><text x="68" y="118" text-anchor="middle" fill="#415d52" font-size="10">AGENT</text><text x="281" y="118" text-anchor="middle" fill="#415d52" font-size="10">SERVER</text><text x="175" y="195" text-anchor="middle" fill="#a44c34" font-size="9" letter-spacing="2">TRUST / TRANSPORT / TLS</text><text x="18" y="223" fill="#617266" class="art-caption">01 — SECURITY BOUNDARIES · CONCEPT</text></svg>';
 if(type==='star'){let dots='';for(let i=0;i<18;i++){let x=140+(i*37%79),y=68+(i*29%96);dots+=`<circle cx="${x}" cy="${y}" r="${i%3===0?3.5:2.5}" fill="${i%2?'#a44c34':'#456b5d'}" opacity=".75"/>`;}return start+`<rect width="350" height="239" fill="#e6ebe2"/><g fill="none" stroke="#b7c6b5"><ellipse cx="175" cy="114" rx="67" ry="63"/><ellipse cx="175" cy="114" rx="94" ry="40" transform="rotate(-25 175 114)"/><path d="M24 113H98M252 113H326" stroke-dasharray="3 4"/></g>${dots}<g stroke="#486e5f" stroke-width="2"><path d="M33 103v20m7-27v32m7-20v13m7-32v43m7-30v25m7-17v10m7-26v35"/></g><g fill="none" stroke="#a44c34"><rect x="274" y="87" width="39" height="49" rx="2"/><path d="M281 97h25m-25 9h16m-16 9h25m-25 9h20"/></g><text x="54" y="157" text-anchor="middle" font-size="8" fill="#486e5f">TRAFFIC</text><text x="295" y="157" text-anchor="middle" font-size="8" fill="#a44c34">SEMANTICS</text><text x="175" y="193" text-anchor="middle" fill="#486e5f" font-size="9" letter-spacing="2">A SHARED REPRESENTATION</text><text x="18" y="223" fill="#617266" class="art-caption">02 — CROSS-MODAL ALIGNMENT · CONCEPT</text></svg>`;}
 let bars='';for(let row=0;row<3;row++)for(let col=0;col<24;col++){const height=6+((col*13+row*19)%29);bars+=`<rect x="${91+col*8}" y="${58+row*49+34-height}" width="4" height="${height}" rx="1" fill="${['#365c58','#7d9271','#ac624a'][row]}"/>`;}
 return start+`<rect width="350" height="239" fill="#e8eae4"/><g stroke="#cbd2c6"><path d="M84 92H300M84 141H300M84 190H300"/></g>${bars}<g font-size="9" fill="#486052"><text x="34" y="79">HTTP/1.1</text><text x="34" y="128">HTTP/2</text><text x="34" y="177">HTTP/3</text></g><text x="18" y="223" fill="#617266" class="art-caption">03 — PROTOCOL PARALLELISM · CONCEPT</text></svg>`;
}
let language='en';
try {language=localStorage.getItem('language')==='zh'?'zh':'en';}catch{}
const originalText=new Map();
document.querySelectorAll('[data-i18n]').forEach(el=>originalText.set(el,el.innerHTML));
const role=document.querySelector('[data-i18n="role"]');originalText.set(role,'PH.D. STUDENT · NETWORK SECURITY');
const bio=document.querySelector('[data-i18n="bio"]');originalText.set(bio,'I am a Ph.D. student at the Institute of Information Engineering, Chinese Academy of Sciences, and the University of Chinese Academy of Sciences, advised by Qingyun Liu (Professor-level Senior Engineer). My research focuses on website fingerprinting, encrypted traffic analysis, and network protocol security.');
const education=document.createElement('div');education.className='education';education.dataset.i18n='education';originalText.set(education,'<strong>IIE, Chinese Academy of Sciences / UCAS</strong>Master’s studies, 2021 · Ph.D. track, 2023<br>Expected graduation: January 2027');document.querySelector('.about-text').after(education);
const nextStep=document.createElement('p');nextStep.className='next-step';nextStep.dataset.i18n='nextStep';originalText.set(nextStep,'Incoming at Zhongguancun Laboratory, in Academician Xiaochun Yun’s team.');education.after(nextStep);
function render(){
 const zh=language==='zh',idx=zh?1:0;
 document.documentElement.lang=zh?'zh-CN':'en';
 document.title=zh?'程逸飞 · 网络安全研究':'Yifei Cheng · Security Research';
 originalText.forEach((value,el)=>el.innerHTML=zh?(translations[el.dataset.i18n]||value):value);
 document.querySelector('.intro').innerHTML=zh?'你好，我是程逸飞。':'Hello, I’m Yifei Cheng. <span class="chinese-name">程逸飞</span>';
 const toggle=document.getElementById('language');toggle.innerHTML=zh?'EN <span>↗</span>':'中文 <span>↗</span>';toggle.setAttribute('aria-label',zh?'Switch to English':'切换为中文');
 document.querySelector('nav').setAttribute('aria-label',zh?'主导航':'Main navigation');
 document.querySelector('.skip').textContent=zh?'跳至正文':'Skip to content';
 document.getElementById('close-citation').setAttribute('aria-label',zh?'关闭引用':'Close citation');
 document.getElementById('copy-citation').textContent=zh?'复制引用':'Copy citation';
 document.getElementById('featured-papers').innerHTML=papers.map((p,i)=>`<article class="paper" id="paper-${p.id}"><div class="paper-art">${p.image?`<img src="${p.image}" alt="${p.name} research overview" loading="lazy" width="350" height="239">`:illustration(p.art)}</div><div><div class="paper-meta"><span class="venue">${p.venue}</span>${p.status?`<span class="status">${p.status[idx]}</span>`:''}<span>${zh?'第一作者':'FIRST AUTHOR'}</span></div><h3>${p.name}</h3><p class="paper-subtitle">${p.subtitle}</p><p class="authors">${p.authors||(zh?'<strong>程逸飞</strong> 等':'<strong>Yifei Cheng</strong> et al.')}</p><p class="paper-summary">${p.summary[idx]}</p><div class="paper-links">${p.links.map(l=>`<a href="${l[2]}" target="_blank" rel="noopener noreferrer">${l[idx]} ↗</a>`).join('')}${p.bib?`<button data-cite="${i}" aria-haspopup="dialog">BibTeX ↗</button>`:`<span class="availability">${zh?'已录用 · 论文链接将在公开后补充':'Accepted · paper link forthcoming'}</span>`}</div></div></article>`).join('');
 document.getElementById('additional-papers').innerHTML=additional.map(p=>`<article class="compact-paper"><span class="year">${p[0]}</span><div><h4>${p[1]}</h4><p>${zh?`第${['','一','二','三','四'][p[3]]}作者`:`${{1:'First',2:'Second',4:'Fourth'}[p[3]]} author`}${p[4]?(zh?' · 已录用':' · Accepted'):''}</p></div><span class="compact-venue">${p[2]}</span></article>`).join('');
 document.querySelectorAll('[data-cite]').forEach(btn=>btn.addEventListener('click',()=>{document.getElementById('citation-text').textContent=papers[Number(btn.dataset.cite)].bib;document.getElementById('copy-status').textContent='';document.getElementById('citation-dialog').showModal();}));
}
document.getElementById('language').addEventListener('click',()=>{language=language==='en'?'zh':'en';try{localStorage.setItem('language',language);}catch{}render();});
document.getElementById('close-citation').addEventListener('click',()=>document.getElementById('citation-dialog').close());
document.getElementById('citation-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
document.getElementById('copy-citation').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.getElementById('citation-text').textContent);document.getElementById('copy-status').textContent=language==='zh'?'已复制到剪贴板。':'Copied to clipboard.';}catch{document.getElementById('copy-status').textContent=language==='zh'?'请选中上方文本，手动复制。':'Please select and copy the citation above.';}});
const traceGroup=document.getElementById('trace-lines');
for(let i=0;i<25;i++){let d='';for(let x=12;x<=466;x+=3){const envelope=Math.exp(-Math.pow((x-255)/135,2));const y=210+(i-12)*10+Math.sin(x/38+i*.19)*envelope*41+Math.sin(x/15+i*.32)*envelope*8;d+=(x===12?'M':'L')+x+' '+y.toFixed(2)+' ';}const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d);path.setAttribute('fill','none');path.setAttribute('stroke',i%6===0?'#a66a4c':'url(#trace-gradient)');path.setAttribute('stroke-width',i%6===0?'1.3':'.85');traceGroup.append(path);}
render();
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal');observer.unobserve(e.target);}}),{threshold:.1});document.querySelectorAll('.paper,.section-heading,.about-grid,.contact-row').forEach(el=>observer.observe(el));}
