const papers = [
  {id:'silent',name:'Silent Surrender',subtitle:'Measuring MitM-Induced TLS Downgrades in LLM Agents',venue:'NDSS 2027',status:['ACCEPTED','已录用'],authors:'<strong>Yifei Cheng</strong>, Xinhao Deng, Yujia Zhu, Baiyang Li, Yaochen Ren, Gang Xiong, Zhen Li, Jiang Xie, Xixun Lin, Qingyun Liu',summary:['Examining TLS security boundaries in LLM agents through measurement of man-in-the-middle-induced downgrades.','通过测量中间人诱导的 TLS 降级行为，研究大语言模型智能体的通信安全边界。'],links:[],art:'tls'},
  {id:'star',name:'STAR',subtitle:'Semantic-Traffic Alignment and Retrieval for Zero-Shot HTTPS Website Fingerprinting',venue:'INFOCOM 2026',authors:'<strong>Yifei Cheng</strong>, Yujia Zhu, Baiyang Li, Xinhao Deng, Yitong Cai, Yaochen Ren, Qingyun Liu',summary:['Recognizing unseen websites by aligning encrypted traffic with website semantics — without collecting training traffic from the target sites.','将加密流量与网站语义对齐，在无需采集目标网站训练流量的情况下识别未见网站。'],links:[['Paper','论文','https://arxiv.org/abs/2512.17667'],['Code','代码','https://github.com/2654400439/STAR-Website-Fingerprinting'],['Dataset','数据集','https://doi.org/10.5281/zenodo.17060855']],bib:'@inproceedings{cheng2026star,\n  title={STAR: Semantic-Traffic Alignment and Retrieval for Zero-Shot HTTPS Website Fingerprinting},\n  author={Cheng, Yifei and Zhu, Yujia and Li, Baiyang and Deng, Xinhao and Cai, Yitong and Ren, Yaochen and Liu, Qingyun},\n  booktitle={IEEE INFOCOM 2026-IEEE Conference on Computer Communications},\n  pages={1--10},\n  year={2026},\n  organization={IEEE}\n}',art:'star'},
  {id:'holmes',name:'HOLMES & WATSON',subtitle:'A Robust and Lightweight HTTPS Website Fingerprinting through HTTP Version Parallelism',venue:'WWW 2025',status:['ORAL','口头报告'],authors:'<strong>Yifei Cheng</strong>, Yujia Zhu, Baiyang Li, Peishuai Sun, Yong Ding, Xinhao Deng, Qingyun Liu',summary:['Using the parallel behavior of HTTP versions to build compact, robust fingerprints of encrypted website visits.','利用 HTTP 多版本并行行为，构建轻量、鲁棒的加密网站访问指纹。'],links:[['Paper','论文','https://doi.org/10.1145/3696410.3714578'],['Code','代码','https://github.com/2654400439/H123-Website-Fingerprinting'],['Dataset','数据集','https://zenodo.org/records/14727250']],bib:'@inproceedings{cheng2025holmes,\n  title={HOLMES \\& WATSON: A Robust and Lightweight HTTPS Website Fingerprinting through HTTP Version Parallelism},\n  author={Cheng, Yifei and Zhu, Yujia and Li, Baiyang and Sun, Peishuai and Ding, Yong and Deng, Xinhao and Liu, Qingyun},\n  booktitle={Proceedings of the ACM on Web Conference 2025},\n  pages={1078--1092},\n  year={2025},\n  doi={10.1145/3696410.3714578}\n}',art:'holmes'}
];
const additional = [
  ['2026','How Web Optimization Shapes Encrypted Traffic Observability','WISE 2026',1,true],
  ['2026','Beyond the clean slate: robust website fingerprinting via cache-time trajectories','WISE 2026',1,true],
  ['2026','OPTICS: Open-set Encrypted Traffic Classification via Conditional Diffusion Models','ICNP 2026',4,true],
  ['2025','Knocking on IP: Unveiling Websites through Cache-Aware Fingerprinting','ICASSP 2025',2,false],
  ['2025','QUIC安全研究综述：协议、实现和生态','通信学报',2,false]
];

additional.push(['2023','DRDoSHunter: A Novel Approach Based on FDA and Inter-flow Features for DRDoS Detection','ISCC 2023',1,false]);
